package com.vku.eventmanagement.common.exception;

public enum ErrorCode {

  // ===== Common / System =====
  COMMON_VALIDATION_ERROR,
  COMMON_MALFORMED_JSON,
  COMMON_MISSING_PARAMETER,
  COMMON_DATA_INTEGRITY_VIOLATION,
  COMMON_NOT_FOUND,
  COMMON_INTERNAL_ERROR,

  // ===== Auth / Security =====
  AUTH_UNAUTHORIZED,
  AUTH_FORBIDDEN,
  AUTH_INVALID_CREDENTIALS,
  AUTH_TOKEN_EXPIRED,
  AUTH_INVALID_TOKEN,
  AUTH_ACCOUNT_SUSPENDED,

  // ===== User =====
  USER_NOT_FOUND,
  USER_EMAIL_ALREADY_EXISTS,

  // ===== Event (future) =====
  EVENT_NOT_FOUND,
  EVENT_ACCESS_DENIED,

  // ===== Attendance (future) =====
  ATTENDANCE_ALREADY_CHECKED_IN,
  ATTENDANCE_NOT_REGISTERED
}
