steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "gcr.io/$PROJECT_ID/bophieu-api:$SHORT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/bophieu-api:latest"
      - "."
    id: "build-image"

  # Push image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/bophieu-api:$SHORT_SHA"
    id: "push-image-versioned"
    waitFor: ["build-image"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/bophieu-api:latest"
    id: "push-image-latest"
    waitFor: ["build-image"]

  # Set kubectl context
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/eventmanagement-api"
      - "eventmanagement-api=gcr.io/$PROJECT_ID/bophieu-api:$SHORT_SHA"
      - "--namespace=eventmanagement"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=event-management-cluster"
    id: "deploy-to-gke"
    waitFor: ["push-image-versioned", "push-image-latest"]

  # Rollout status check
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "rollout"
      - "status"
      - "deployment/eventmanagement-api"
      - "--namespace=eventmanagement"
      - "--timeout=5m"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=event-management-cluster"
    id: "check-rollout"
    waitFor: ["deploy-to-gke"]

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: bophieu-api
  _ZONE: asia-southeast1-a
  _CLUSTER_NAME: bophieu-cluster

timeout: "1200s"

images:
  - "gcr.io/$PROJECT_ID/bophieu-api:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/bophieu-api:latest"
