spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/event_management?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  mail:
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

app:
  jwt:
    secret: ${JWT_SECRET:}
    expirationMs: 900000
    refreshExpirationMs: 604800000
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000"
  frontend:
    url: http://localhost:5173

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

gemini:
  api:
    key: ${GEMINI_API_KEY:}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
